# Site settings
title: Hujin Blog
SEOTitle: 胡进的博客 | Hujin's Blog
header-img: img/home-bg.jpg
email: guokehujin@163.com
description: "Hujin，Openstack & SDN & Kubernetes Lover，Software Engineer，| 与你一起发现更大的世界"
keyword: "Openstack, Kubernetes, Neutron， SDN， Tungsten Fabric"
url: "https://smallcoderhujin.github.io/blog/"
<<<<<<< HEAD
baseurl: "/blog"
=======
baseurl: ""
>>>>>>> c58ceedc0a99cdbe76bbe0027c08ac320c6aed46

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     guokehujin
zhihu_username:     guokehujin
github_username:    guokehujin
twitter_username:   guokehujin
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
timezone: CN



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username:

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: ellen.cf



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "For the next quantum leap<br>离开世界之前，一切都是过程"
sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "test",
        href: "http://baidu.com/"
    },
]

theme: jekyll-theme-cayman
